---
pull_secret_path: "/tmp/pull-secret.txt"
pull_secret: "{{ lookup('ansible.builtin.file', pull_secret_path) | to_json }}"
offline_token_path: "/tmp/offline-token.txt"
offline_token: "{{ lookup('ansible.builtin.file', offline_token_path ) }}"
ssh_authorized_key_path: "{{ '~/.ssh/id_rsa.pub' | expanduser }}"
ssh_authorized_key: "{{ lookup('ansible.builtin.file', ssh_authorized_key_path ) }}"
cluster_domain: "ocpclusters.dev.redhatworkshops.io"
cluster_version: "4.13"
cluster_iso_type: "minimal-iso"
dns_zone: "dev.redhatworkshops.io"
ocp_namespace: "vmexamples"
ocp_vmname_sno: "sno-{{ cluster_name }}"
ocp_vmname_master_prefix: "master-{{ cluster_name }}"
ocp_vmname_worker_prefix: "worker-{{ cluster_name }}"
action: "create"
output_dir: "{{ '~/.kube/clusters' | expanduser }}"
overwrite_dns: false
masters_macs:
  - ""
  - "{{ 'f6:45:ae' | community.general.random_mac(ocp_namespace + cluster_name + 'm1') }}"
  - "{{ 'f6:45:ae' | community.general.random_mac(ocp_namespace + cluster_name + 'm2') }}"
  - "{{ 'f6:45:ae' | community.general.random_mac(ocp_namespace + cluster_name + 'm3') }}"
workers_macs:
  - ""
  - "{{ 'f6:45:ae' | community.general.random_mac(ocp_namespace + cluster_name + 'w1') }}"
  - "{{ 'f6:45:ae' | community.general.random_mac(ocp_namespace + cluster_name + 'w2') }}"
  - "{{ 'f6:45:ae' | community.general.random_mac(ocp_namespace + cluster_name + 'w3') }}"
