---
- hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - vars/config.yaml
  vars_prompt:
    - name: cluster_name
      prompt: Specify cluster name
      private: false
  tasks:
    - name: Destroy Compact cluster
      when: action == "delete" or action == "destroy"
      block:
        - name: Delete the service (type LoadBalancer) for Compact
          kubernetes.core.k8s:
            state: absent
            api_version: v1
            kind: Service
            namespace: "{{ ocp_namespace }}"
            name: "{{ ocp_vmname_master_prefix }}-svc"

        - name: Delete CNAME dns record
          amazon.aws.route53:
            state: absent
            zone: "{{ dns_zone }}"
            record: "{{ item }}.{{ cluster_name}}.{{ cluster_domain }}"
            type: CNAME
          loop:
            - "api"
            - "*.apps"

        - name: Delete a Compact VM
          kubernetes.core.k8s:
            state: absent
            api_version: v1
            kind: VirtualMachine
            namespace: "{{ ocp_namespace }}"
            name: "{{ ocp_vmname_master_prefix }}-{{ _index }}"
          loop: "{{ query('sequence', 'start=1 end=3') }}"
          loop_control:
            loop_var: _index


        - name: Remove Assisted Installer Cluster
          agonzalezrh.install_openshift.delete_cluster:
            cluster_id: "{{ cluster_id }}"
            offline_token: "{{ offline_token }}"


    - name: Create Compact cluster
      when: action == "create"
      block:
        - name: Add the service (type LoadBalancer) for Compact
          kubernetes.core.k8s:
            definition: "{{ lookup('ansible.builtin.template', 'templates/compact_svc.yaml') }}"
            wait: true
            wait_timeout: 300
          vars:
            svcname: "{{ ocp_vmname_master_prefix }}-svc"
            namespace: "{{ ocp_namespace }}"

        - name: Wait for the LoadBalancer value
          register: compact_svc
          kubernetes.core.k8s_info:
            api_version: v1
            kind: Service
            name: "{{ ocp_vmname_master_prefix }}-svc"
            namespace: "{{ ocp_namespace }}"
          until: compact_svc.resources[0].status.loadBalancer.ingress[0].hostname | default('') != ''
          retries: 10
          delay: 2

        - name: Add CNAME dns record
          amazon.aws.route53:
            state: present
            zone: "{{ dns_zone }}"
            record: "{{ item }}.{{ cluster_name}}.{{ cluster_domain }}"
            type: CNAME
            value: "{{ compact_svc.resources[0].status.loadBalancer.ingress[0].hostname }}"
            ttl: 30
          loop:
            - "api"
            - "*.apps"

        - name: Create OVN secondary network
          kubernetes.core.k8s:
            definition: "{{ lookup('ansible.builtin.template', 'templates/net-attach-def.yaml') }}"
            wait: true
            wait_timeout: 300
          vars:
            network_name: "{{ cluster_name }}-openshift"
            namespace: "{{ ocp_namespace }}"

        - name: Create Assisted Installer Cluster
          agonzalezrh.install_openshift.create_cluster:
            name: "{{ cluster_name }}"
            openshift_version: "{{ cluster_version }}"
            base_dns_domain: "{{ cluster_domain }}"
            offline_token: "{{ offline_token }}"
            pull_secret: "{{ pull_secret }}"
            olm_operators:
              - name: "odf"
            high_availability_mode: "Full"
            schedulable_masters: true
            service_networks:
              - cidr: "172.31.0.0/16"
            machine_networks:
              - cidr: "10.10.10.0/24"
            api_vip: 10.10.10.100
            api_vips:
              - ip: 10.10.10.100
            ingress_vip: 10.10.10.101
            ingress_vips:
              - ip: 10.10.10.101
          register: newcluster

        - name: Include vars
          include_vars:
            file: vars/static_network_config_compact.yaml

        - name: Create Infrastructure environment
          agonzalezrh.install_openshift.create_infra_env:
            name: "{{ cluster_name }}-infra-env"
            image_type: "{{ cluster_iso_type }}"
            cluster_id: "{{ newcluster.result.id }}"
            ssh_authorized_key: "{{ ssh_authorized_key }}"
            offline_token: "{{ offline_token }}"
            pull_secret: "{{ pull_secret }}"
            static_network_config: "{{ static_network_config }}"
          register: newinfraenv

        - name: Create a three master VMs for Compact cluster
          kubernetes.core.k8s:
            definition: "{{ lookup('ansible.builtin.template', 'templates/masters-compact-odf.yaml') }}"
            wait: true
            wait_timeout: 300
            wait_condition:
              status: true
              type: Ready
          vars:
            image_url: "{{ newinfraenv.result.download_url }}"
            vmname: "{{ ocp_vmname_master_prefix }}-{{ _index }}"
            namespace: "{{ ocp_namespace }}"
            storageclass: "gp3-csi"
            network: "{{ cluster_name}}-openshift"
            network_name: "{{ cluster_name }}-openshift"
            pod_network: "192.168.{{ _index }}.0/24"
          loop: "{{ query('sequence', 'start=1 end=3') }}"
          loop_control:
            loop_var: _index


        - name: Wait for the hosts to be ready
          agonzalezrh.install_openshift.wait_for_hosts:
            cluster_id: "{{ newcluster.result.id }}"
            infra_env_id: "{{ newinfraenv.result.id }}"
            offline_token: "{{ offline_token }}"
            expected_hosts: 3
            configure_hosts:
              - hostname: master-{{ cluster_name }}-1
                role: master
                installation_disk: /dev/vda
              - hostname: master-{{ cluster_name }}-2
                role: master
                installation_disk: /dev/vda
              - hostname: master-{{ cluster_name }}-3
                role: master
                installation_disk: /dev/vda
            wait_timeout: 600

        - name: Start cluster installation
          agonzalezrh.install_openshift.install_cluster:
            cluster_id: "{{ newcluster.result.id }}"
            offline_token: "{{ offline_token }}"
            wait_timeout: 1200

        - name: Obtain OpenShift cluster credentials
          register: credentials
          agonzalezrh.install_openshift.get_credentials:
            cluster_id: "{{ newcluster.result.id }}"
            offline_token: "{{ offline_token }}"

        - name: Display credentials
          debug:
            var: credentials.result

        - name: Create directory for downloaded credential files
          ansible.builtin.file:
            state: directory
            path: "{{ output_dir }}/{{ cluster_name }}"
            recurse: true

        - name: Downloads OpenShift cluster credentials
          agonzalezrh.install_openshift.download_credentials:
            cluster_id: "{{ newcluster.result.id }}"
            offline_token: "{{ offline_token }}"
            file_name: "{{ item }}"
            dest: "{{ output_dir }}/{{ cluster_name }}/{{ item }}"
          loop:
            - kubeadmin-password
            - kubeconfig
            - kubeconfig-noingress

        - name: Downloads OpenShift cluster files
          agonzalezrh.install_openshift.download_files:
            cluster_id: "{{ newcluster.result.id }}"
            offline_token: "{{ offline_token }}"
            file_name: "{{ item }}"
            dest: "{{ output_dir }}/{{ cluster_name }}/{{ item }}"
          loop:
            - bootstrap.ign
            - master.ign
            - metadata.json
            - worker.ign
            - install-config.yaml
            - custom_manifests.json
            - custom_manifests.yaml
