---
- hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - vars/config.yaml
  tasks:
    - name: Get a list of clusters
      agonzalezrh.install_openshift.list_clusters:
        offline_token: "{{ offline_token }}"
      register: listclusters

    - name: Show the created clusters and the status
      debug:
        msg: "ansible-playbook full_kubevirt.yaml -e action='delete' -e cluster_id={{ item.id }} -e cluster_name={{ item.name }}"
      loop: "{{ listclusters.result }}"
      loop_control:
        label: "{{ item.name }}"
