- hosts: localhost
  gather_facts: False
  tasks:
    - name: Create directory for downloaded credential files
      ansible.builtin.file:
        state: directory
        path: "{{ output_dir }}/{{ cluster_name }}"
        recurse: true

    - name: Downloads OpenShift cluster credentials
      agonzalezrh.install_openshift.download_credentials:
        cluster_id: "{{ cluster_id }}"
        offline_token: "{{ offline_token }}"
        file_name: "{{ item }}"
        dest: "{{ output_dir }}/{{ cluster_name }}/{{ item }}"
      loop:
        - kubeadmin-password
        - kubeconfig
        - kubeconfig-noingress
